use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'VideoConsultationSDK_Example' do
  pod 'VideoConsultationSDK', :path => '../'
  pod 'ZLPhotoBrowser','~> 3.1.4'
  pod 'MBProgressHUD'
end
