#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VideoConsultation",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC17VideoConsultation10DoctorInfo")
@interface DoctorInfo : NSObject
/// 医生ID
@property (nonatomic, copy) NSString * _Nullable doctorId;
/// 医生姓名
@property (nonatomic, copy) NSString * _Nullable doctorName;
/// 医生头像
@property (nonatomic, copy) NSString * _Nullable doctorHeadUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC17VideoConsultation11MedicalInfo")
@interface MedicalInfo : NSObject
/// 咨询疾病名称
@property (nonatomic, copy) NSString * _Nullable consultDisease;
/// 咨询内容
@property (nonatomic, copy) NSString * _Nullable consultContent;
/// 咨询附件图片
@property (nonatomic, copy) NSArray<UIImage *> * _Nullable attachmentImage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17VideoConsultation6Member")
@interface Member : NSObject
/// 姓名
@property (nonatomic, copy) NSString * _Nullable name;
/// 性别（0-男、1-女、2-未知
@property (nonatomic, copy) NSString * _Nullable gender;
/// 生日
@property (nonatomic, copy) NSString * _Nullable birthday;
/// 手机或身份证选其一
@property (nonatomic, copy) NSString * _Nullable phone;
/// 手机或身份证选其一
@property (nonatomic, copy) NSString * _Nullable idNumber;
/// 头像
@property (nonatomic, copy) NSString * _Nullable headUrl;
/// 过敏史
@property (nonatomic, copy) NSString * _Nullable allergicRemark;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 任务类型
/// <ul>
///   <li>
///     login: 登录
///   </li>
///   <li>
///     checkMember: 提交会员信息
///   </li>
///   <li>
///     uploadImage: 上传图片
///   </li>
///   <li>
///     createOrder: 创建预约
///   </li>
///   <li>
///     getRegister: 获取预约详情
///   </li>
///   <li>
///     getRecipeList: 获取处方内容
///   </li>
///   <li>
///     getRecipeFiles: 下载处方PDF文件
///   </li>
///   <li>
///     getRoomWaitCout: 获取诊室候诊人数量
///   </li>
/// </ul>
typedef SWIFT_ENUM_NAMED(NSInteger, TaskType, "TaskType", closed) {
  TaskTypeLogin = 0,
  TaskTypeCheckMember = 1,
  TaskTypeUploadImage = 2,
  TaskTypeCreateOrder = 3,
  TaskTypeGetRegister = 4,
  TaskTypeGetRecipeList = 5,
  TaskTypeGetRecipeFiles = 6,
  TaskTypeGetRoomWaitCout = 7,
};


SWIFT_CLASS("_TtC17VideoConsultation7VCParam")
@interface VCParam : NSObject
/// 房间ID
@property (nonatomic, copy) NSString * _Null_unspecified channleId;
/// 预约ID
@property (nonatomic, copy) NSString * _Null_unspecified registerID;
/// 就诊人
@property (nonatomic, strong) Member * _Null_unspecified member;
/// 医生
@property (nonatomic, strong) DoctorInfo * _Null_unspecified doctor;
/// 看诊信息
@property (nonatomic, strong) MedicalInfo * _Null_unspecified medicalInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface VCParam (SWIFT_EXTENSION(VideoConsultation))
- (NSDictionary<NSString *, id> * _Nonnull)checkMemberParam SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getOrderParam SWIFT_WARN_UNUSED_RESULT;
@end

@class UINavigationController;
@class NSProgress;

SWIFT_CLASS("_TtC17VideoConsultation24VideoConsultationManager")
@interface VideoConsultationManager : NSObject
/// 相关参数
@property (nonatomic, strong) VCParam * _Null_unspecified param;
/// 承载容器
@property (nonatomic, strong) UINavigationController * _Null_unspecified showVC;
/// 任务状态回调
@property (nonatomic, copy) void (^ _Nullable taskHandler)(NSString * _Nullable, NSProgress * _Nullable, BOOL);
+ (VideoConsultationManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// 登录
/// \param number 账户名或账户唯一标记,登录时必要参数
///
/// \param handler CompleteHandler
///
- (void)loginWithNumber:(NSString * _Null_unspecified)number handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 创建订单
/// Member * member = [[Member alloc]init];
/// member.phone = @“13760291826”;
/// member.birthday = @“2001-01-09”;
/// member.name = @“林祥”;
/// member.gender = @“男”;
/// member.allergicRemark = @“花粉过敏,等等”;
/// DoctorInfo * doctor = [[DoctorInfo alloc]init];
/// doctor.doctorId = @“78ee0381bbb541aba41fbc2ecb4566ba”;
/// MedicalInfo *medicalInfo = [[MedicalInfo alloc]init];
/// medicalInfo.consultDisease = @“感冒sssss”;
/// medicalInfo.consultContent = @“流鼻涕，很难受，而且头很痛ssssss流鼻涕，很难受，而且头很痛ssssss流鼻涕，很难受，而且头很痛ssssss流鼻涕”;
/// medicalInfo.attachmentImage = self.imagesArr;
/// VCParam * param = [[VCParam alloc]init];
/// param.member = member;
/// param.doctor = doctor;
/// param.medicalInfo = medicalInfo;
/// \param param VCParam
///
/// \param handler CompleteHandler
///
- (void)createOrder:(VCParam * _Null_unspecified)param handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 进入诊室
/// \param channleID 房间ID
///
/// \param doctorID 医生ID
///
/// \param showVC UINavigationController
///
/// \param handler CompleteHandler
///
- (void)enterConsultationRoomWithChannleID:(NSInteger)channleID doctorID:(NSString * _Nonnull)doctorID showVC:(UINavigationController * _Nonnull)showVC handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 查询订单详情
/// 通过字段[RecipeFileUrl] 判断是否已开处方
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getRegistersInfoWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 获取处方内容
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getRecipeFilesWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 下载处方PDF
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getFilesDownloadWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 获取当前诊室候诊人数
/// \param channleID 房间ID
///
/// \param doctorID 医生ID
///
/// \param handler CompleteHandler
///
- (void)getRoomWaitCountWithChannleID:(NSInteger)channleID doctorID:(NSString * _Nonnull)doctorID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 清理文件
///
/// returns:
/// 结果 BOOL
- (BOOL)removeFilePDF SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VideoConsultation",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC17VideoConsultation10DoctorInfo")
@interface DoctorInfo : NSObject
/// 医生ID
@property (nonatomic, copy) NSString * _Nullable doctorId;
/// 医生姓名
@property (nonatomic, copy) NSString * _Nullable doctorName;
/// 医生头像
@property (nonatomic, copy) NSString * _Nullable doctorHeadUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC17VideoConsultation11MedicalInfo")
@interface MedicalInfo : NSObject
/// 咨询疾病名称
@property (nonatomic, copy) NSString * _Nullable consultDisease;
/// 咨询内容
@property (nonatomic, copy) NSString * _Nullable consultContent;
/// 咨询附件图片
@property (nonatomic, copy) NSArray<UIImage *> * _Nullable attachmentImage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17VideoConsultation6Member")
@interface Member : NSObject
/// 姓名
@property (nonatomic, copy) NSString * _Nullable name;
/// 性别（0-男、1-女、2-未知
@property (nonatomic, copy) NSString * _Nullable gender;
/// 生日
@property (nonatomic, copy) NSString * _Nullable birthday;
/// 手机或身份证选其一
@property (nonatomic, copy) NSString * _Nullable phone;
/// 手机或身份证选其一
@property (nonatomic, copy) NSString * _Nullable idNumber;
/// 头像
@property (nonatomic, copy) NSString * _Nullable headUrl;
/// 过敏史
@property (nonatomic, copy) NSString * _Nullable allergicRemark;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 任务类型
/// <ul>
///   <li>
///     login: 登录
///   </li>
///   <li>
///     checkMember: 提交会员信息
///   </li>
///   <li>
///     uploadImage: 上传图片
///   </li>
///   <li>
///     createOrder: 创建预约
///   </li>
///   <li>
///     getRegister: 获取预约详情
///   </li>
///   <li>
///     getRecipeList: 获取处方内容
///   </li>
///   <li>
///     getRecipeFiles: 下载处方PDF文件
///   </li>
///   <li>
///     getRoomWaitCout: 获取诊室候诊人数量
///   </li>
/// </ul>
typedef SWIFT_ENUM_NAMED(NSInteger, TaskType, "TaskType", closed) {
  TaskTypeLogin = 0,
  TaskTypeCheckMember = 1,
  TaskTypeUploadImage = 2,
  TaskTypeCreateOrder = 3,
  TaskTypeGetRegister = 4,
  TaskTypeGetRecipeList = 5,
  TaskTypeGetRecipeFiles = 6,
  TaskTypeGetRoomWaitCout = 7,
};


SWIFT_CLASS("_TtC17VideoConsultation7VCParam")
@interface VCParam : NSObject
/// 房间ID
@property (nonatomic, copy) NSString * _Null_unspecified channleId;
/// 预约ID
@property (nonatomic, copy) NSString * _Null_unspecified registerID;
/// 就诊人
@property (nonatomic, strong) Member * _Null_unspecified member;
/// 医生
@property (nonatomic, strong) DoctorInfo * _Null_unspecified doctor;
/// 看诊信息
@property (nonatomic, strong) MedicalInfo * _Null_unspecified medicalInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface VCParam (SWIFT_EXTENSION(VideoConsultation))
- (NSDictionary<NSString *, id> * _Nonnull)checkMemberParam SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getOrderParam SWIFT_WARN_UNUSED_RESULT;
@end

@class UINavigationController;
@class NSProgress;

SWIFT_CLASS("_TtC17VideoConsultation24VideoConsultationManager")
@interface VideoConsultationManager : NSObject
/// 相关参数
@property (nonatomic, strong) VCParam * _Null_unspecified param;
/// 承载容器
@property (nonatomic, strong) UINavigationController * _Null_unspecified showVC;
/// 任务状态回调
@property (nonatomic, copy) void (^ _Nullable taskHandler)(NSString * _Nullable, NSProgress * _Nullable, BOOL);
+ (VideoConsultationManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// 登录
/// \param number 账户名或账户唯一标记,登录时必要参数
///
/// \param handler CompleteHandler
///
- (void)loginWithNumber:(NSString * _Null_unspecified)number handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 创建订单
/// Member * member = [[Member alloc]init];
/// member.phone = @“13760291826”;
/// member.birthday = @“2001-01-09”;
/// member.name = @“林祥”;
/// member.gender = @“男”;
/// member.allergicRemark = @“花粉过敏,等等”;
/// DoctorInfo * doctor = [[DoctorInfo alloc]init];
/// doctor.doctorId = @“78ee0381bbb541aba41fbc2ecb4566ba”;
/// MedicalInfo *medicalInfo = [[MedicalInfo alloc]init];
/// medicalInfo.consultDisease = @“感冒sssss”;
/// medicalInfo.consultContent = @“流鼻涕，很难受，而且头很痛ssssss流鼻涕，很难受，而且头很痛ssssss流鼻涕，很难受，而且头很痛ssssss流鼻涕”;
/// medicalInfo.attachmentImage = self.imagesArr;
/// VCParam * param = [[VCParam alloc]init];
/// param.member = member;
/// param.doctor = doctor;
/// param.medicalInfo = medicalInfo;
/// \param param VCParam
///
/// \param handler CompleteHandler
///
- (void)createOrder:(VCParam * _Null_unspecified)param handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 进入诊室
/// \param channleID 房间ID
///
/// \param doctorID 医生ID
///
/// \param showVC UINavigationController
///
/// \param handler CompleteHandler
///
- (void)enterConsultationRoomWithChannleID:(NSInteger)channleID doctorID:(NSString * _Nonnull)doctorID showVC:(UINavigationController * _Nonnull)showVC handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 查询订单详情
/// 通过字段[RecipeFileUrl] 判断是否已开处方
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getRegistersInfoWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 获取处方内容
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getRecipeFilesWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 下载处方PDF
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getFilesDownloadWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 获取当前诊室候诊人数
/// \param channleID 房间ID
///
/// \param doctorID 医生ID
///
/// \param handler CompleteHandler
///
- (void)getRoomWaitCountWithChannleID:(NSInteger)channleID doctorID:(NSString * _Nonnull)doctorID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 清理文件
///
/// returns:
/// 结果 BOOL
- (BOOL)removeFilePDF SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VideoConsultation",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC17VideoConsultation10DoctorInfo")
@interface DoctorInfo : NSObject
/// 医生ID
@property (nonatomic, copy) NSString * _Nullable doctorId;
/// 医生姓名
@property (nonatomic, copy) NSString * _Nullable doctorName;
/// 医生头像
@property (nonatomic, copy) NSString * _Nullable doctorHeadUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC17VideoConsultation11MedicalInfo")
@interface MedicalInfo : NSObject
/// 咨询疾病名称
@property (nonatomic, copy) NSString * _Nullable consultDisease;
/// 咨询内容
@property (nonatomic, copy) NSString * _Nullable consultContent;
/// 咨询附件图片
@property (nonatomic, copy) NSArray<UIImage *> * _Nullable attachmentImage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17VideoConsultation6Member")
@interface Member : NSObject
/// 姓名
@property (nonatomic, copy) NSString * _Nullable name;
/// 性别（0-男、1-女、2-未知
@property (nonatomic, copy) NSString * _Nullable gender;
/// 生日
@property (nonatomic, copy) NSString * _Nullable birthday;
/// 手机或身份证选其一
@property (nonatomic, copy) NSString * _Nullable phone;
/// 手机或身份证选其一
@property (nonatomic, copy) NSString * _Nullable idNumber;
/// 头像
@property (nonatomic, copy) NSString * _Nullable headUrl;
/// 过敏史
@property (nonatomic, copy) NSString * _Nullable allergicRemark;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 任务类型
/// <ul>
///   <li>
///     login: 登录
///   </li>
///   <li>
///     checkMember: 提交会员信息
///   </li>
///   <li>
///     uploadImage: 上传图片
///   </li>
///   <li>
///     createOrder: 创建预约
///   </li>
///   <li>
///     getRegister: 获取预约详情
///   </li>
///   <li>
///     getRecipeList: 获取处方内容
///   </li>
///   <li>
///     getRecipeFiles: 下载处方PDF文件
///   </li>
///   <li>
///     getRoomWaitCout: 获取诊室候诊人数量
///   </li>
/// </ul>
typedef SWIFT_ENUM_NAMED(NSInteger, TaskType, "TaskType", closed) {
  TaskTypeLogin = 0,
  TaskTypeCheckMember = 1,
  TaskTypeUploadImage = 2,
  TaskTypeCreateOrder = 3,
  TaskTypeGetRegister = 4,
  TaskTypeGetRecipeList = 5,
  TaskTypeGetRecipeFiles = 6,
  TaskTypeGetRoomWaitCout = 7,
};


SWIFT_CLASS("_TtC17VideoConsultation7VCParam")
@interface VCParam : NSObject
/// 房间ID
@property (nonatomic, copy) NSString * _Null_unspecified channleId;
/// 预约ID
@property (nonatomic, copy) NSString * _Null_unspecified registerID;
/// 就诊人
@property (nonatomic, strong) Member * _Null_unspecified member;
/// 医生
@property (nonatomic, strong) DoctorInfo * _Null_unspecified doctor;
/// 看诊信息
@property (nonatomic, strong) MedicalInfo * _Null_unspecified medicalInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface VCParam (SWIFT_EXTENSION(VideoConsultation))
- (NSDictionary<NSString *, id> * _Nonnull)checkMemberParam SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getOrderParam SWIFT_WARN_UNUSED_RESULT;
@end

@class UINavigationController;
@class NSProgress;

SWIFT_CLASS("_TtC17VideoConsultation24VideoConsultationManager")
@interface VideoConsultationManager : NSObject
/// 相关参数
@property (nonatomic, strong) VCParam * _Null_unspecified param;
/// 承载容器
@property (nonatomic, strong) UINavigationController * _Null_unspecified showVC;
/// 任务状态回调
@property (nonatomic, copy) void (^ _Nullable taskHandler)(NSString * _Nullable, NSProgress * _Nullable, BOOL);
+ (VideoConsultationManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// 登录
/// \param number 账户名或账户唯一标记,登录时必要参数
///
/// \param handler CompleteHandler
///
- (void)loginWithNumber:(NSString * _Null_unspecified)number handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 创建订单
/// Member * member = [[Member alloc]init];
/// member.phone = @“13760291826”;
/// member.birthday = @“2001-01-09”;
/// member.name = @“林祥”;
/// member.gender = @“男”;
/// member.allergicRemark = @“花粉过敏,等等”;
/// DoctorInfo * doctor = [[DoctorInfo alloc]init];
/// doctor.doctorId = @“78ee0381bbb541aba41fbc2ecb4566ba”;
/// MedicalInfo *medicalInfo = [[MedicalInfo alloc]init];
/// medicalInfo.consultDisease = @“感冒sssss”;
/// medicalInfo.consultContent = @“流鼻涕，很难受，而且头很痛ssssss流鼻涕，很难受，而且头很痛ssssss流鼻涕，很难受，而且头很痛ssssss流鼻涕”;
/// medicalInfo.attachmentImage = self.imagesArr;
/// VCParam * param = [[VCParam alloc]init];
/// param.member = member;
/// param.doctor = doctor;
/// param.medicalInfo = medicalInfo;
/// \param param VCParam
///
/// \param handler CompleteHandler
///
- (void)createOrder:(VCParam * _Null_unspecified)param handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 进入诊室
/// \param channleID 房间ID
///
/// \param doctorID 医生ID
///
/// \param showVC UINavigationController
///
/// \param handler CompleteHandler
///
- (void)enterConsultationRoomWithChannleID:(NSInteger)channleID doctorID:(NSString * _Nonnull)doctorID showVC:(UINavigationController * _Nonnull)showVC handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 查询订单详情
/// 通过字段[RecipeFileUrl] 判断是否已开处方
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getRegistersInfoWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 获取处方内容
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getRecipeFilesWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 下载处方PDF
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getFilesDownloadWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 获取当前诊室候诊人数
/// \param channleID 房间ID
///
/// \param doctorID 医生ID
///
/// \param handler CompleteHandler
///
- (void)getRoomWaitCountWithChannleID:(NSInteger)channleID doctorID:(NSString * _Nonnull)doctorID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 清理文件
///
/// returns:
/// 结果 BOOL
- (BOOL)removeFilePDF SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VideoConsultation",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC17VideoConsultation10DoctorInfo")
@interface DoctorInfo : NSObject
/// 医生ID
@property (nonatomic, copy) NSString * _Nullable doctorId;
/// 医生姓名
@property (nonatomic, copy) NSString * _Nullable doctorName;
/// 医生头像
@property (nonatomic, copy) NSString * _Nullable doctorHeadUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC17VideoConsultation11MedicalInfo")
@interface MedicalInfo : NSObject
/// 咨询疾病名称
@property (nonatomic, copy) NSString * _Nullable consultDisease;
/// 咨询内容
@property (nonatomic, copy) NSString * _Nullable consultContent;
/// 咨询附件图片
@property (nonatomic, copy) NSArray<UIImage *> * _Nullable attachmentImage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17VideoConsultation6Member")
@interface Member : NSObject
/// 姓名
@property (nonatomic, copy) NSString * _Nullable name;
/// 性别（0-男、1-女、2-未知
@property (nonatomic, copy) NSString * _Nullable gender;
/// 生日
@property (nonatomic, copy) NSString * _Nullable birthday;
/// 手机或身份证选其一
@property (nonatomic, copy) NSString * _Nullable phone;
/// 手机或身份证选其一
@property (nonatomic, copy) NSString * _Nullable idNumber;
/// 头像
@property (nonatomic, copy) NSString * _Nullable headUrl;
/// 过敏史
@property (nonatomic, copy) NSString * _Nullable allergicRemark;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 任务类型
/// <ul>
///   <li>
///     login: 登录
///   </li>
///   <li>
///     checkMember: 提交会员信息
///   </li>
///   <li>
///     uploadImage: 上传图片
///   </li>
///   <li>
///     createOrder: 创建预约
///   </li>
///   <li>
///     getRegister: 获取预约详情
///   </li>
///   <li>
///     getRecipeList: 获取处方内容
///   </li>
///   <li>
///     getRecipeFiles: 下载处方PDF文件
///   </li>
///   <li>
///     getRoomWaitCout: 获取诊室候诊人数量
///   </li>
/// </ul>
typedef SWIFT_ENUM_NAMED(NSInteger, TaskType, "TaskType", closed) {
  TaskTypeLogin = 0,
  TaskTypeCheckMember = 1,
  TaskTypeUploadImage = 2,
  TaskTypeCreateOrder = 3,
  TaskTypeGetRegister = 4,
  TaskTypeGetRecipeList = 5,
  TaskTypeGetRecipeFiles = 6,
  TaskTypeGetRoomWaitCout = 7,
};


SWIFT_CLASS("_TtC17VideoConsultation7VCParam")
@interface VCParam : NSObject
/// 房间ID
@property (nonatomic, copy) NSString * _Null_unspecified channleId;
/// 预约ID
@property (nonatomic, copy) NSString * _Null_unspecified registerID;
/// 就诊人
@property (nonatomic, strong) Member * _Null_unspecified member;
/// 医生
@property (nonatomic, strong) DoctorInfo * _Null_unspecified doctor;
/// 看诊信息
@property (nonatomic, strong) MedicalInfo * _Null_unspecified medicalInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface VCParam (SWIFT_EXTENSION(VideoConsultation))
- (NSDictionary<NSString *, id> * _Nonnull)checkMemberParam SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getOrderParam SWIFT_WARN_UNUSED_RESULT;
@end

@class UINavigationController;
@class NSProgress;

SWIFT_CLASS("_TtC17VideoConsultation24VideoConsultationManager")
@interface VideoConsultationManager : NSObject
/// 相关参数
@property (nonatomic, strong) VCParam * _Null_unspecified param;
/// 承载容器
@property (nonatomic, strong) UINavigationController * _Null_unspecified showVC;
/// 任务状态回调
@property (nonatomic, copy) void (^ _Nullable taskHandler)(NSString * _Nullable, NSProgress * _Nullable, BOOL);
+ (VideoConsultationManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// 登录
/// \param number 账户名或账户唯一标记,登录时必要参数
///
/// \param handler CompleteHandler
///
- (void)loginWithNumber:(NSString * _Null_unspecified)number handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 创建订单
/// Member * member = [[Member alloc]init];
/// member.phone = @“13760291826”;
/// member.birthday = @“2001-01-09”;
/// member.name = @“林祥”;
/// member.gender = @“男”;
/// member.allergicRemark = @“花粉过敏,等等”;
/// DoctorInfo * doctor = [[DoctorInfo alloc]init];
/// doctor.doctorId = @“78ee0381bbb541aba41fbc2ecb4566ba”;
/// MedicalInfo *medicalInfo = [[MedicalInfo alloc]init];
/// medicalInfo.consultDisease = @“感冒sssss”;
/// medicalInfo.consultContent = @“流鼻涕，很难受，而且头很痛ssssss流鼻涕，很难受，而且头很痛ssssss流鼻涕，很难受，而且头很痛ssssss流鼻涕”;
/// medicalInfo.attachmentImage = self.imagesArr;
/// VCParam * param = [[VCParam alloc]init];
/// param.member = member;
/// param.doctor = doctor;
/// param.medicalInfo = medicalInfo;
/// \param param VCParam
///
/// \param handler CompleteHandler
///
- (void)createOrder:(VCParam * _Null_unspecified)param handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 进入诊室
/// \param channleID 房间ID
///
/// \param doctorID 医生ID
///
/// \param showVC UINavigationController
///
/// \param handler CompleteHandler
///
- (void)enterConsultationRoomWithChannleID:(NSInteger)channleID doctorID:(NSString * _Nonnull)doctorID showVC:(UINavigationController * _Nonnull)showVC handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 查询订单详情
/// 通过字段[RecipeFileUrl] 判断是否已开处方
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getRegistersInfoWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 获取处方内容
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getRecipeFilesWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 下载处方PDF
/// \param registerID 预约ID
///
/// \param handler CompleteHandler
///
- (void)getFilesDownloadWithRegisterID:(NSString * _Nonnull)registerID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 获取当前诊室候诊人数
/// \param channleID 房间ID
///
/// \param doctorID 医生ID
///
/// \param handler CompleteHandler
///
- (void)getRoomWaitCountWithChannleID:(NSInteger)channleID doctorID:(NSString * _Nonnull)doctorID handler:(void (^ _Nonnull)(enum TaskType, id _Nullable, NSError * _Nullable))handler;
/// 清理文件
///
/// returns:
/// 结果 BOOL
- (BOOL)removeFilePDF SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
